### ISSUE TITLE
Inquiry about geting the list of extinct species in the Future Species Extinction Simulation

### ISSUE THREAD

**Issue by XuWeiEvo** [tobiashofmann88/iucnsim#6]
Hi Dr. Andermann,

I would like to know where I can access the list of species that are projected to go extinct in future simulations. Additionally, do I understand correctly that this list may change with each run of the simulation? 

Thank you in advance for your help!

Sincerely, 
Wei Xu

**Comment by tandermann** [comment]
Since it is a probabilistic simulator, there are different species simulated to go extinct in each simulation iteration (as you point out correctly). The extinction probabilities of each species represent the fraction of simulation iterations where that species went extinct and can be found in the file `extinction_probs_over_next_X_years.txt `, e.g. see https://github.com/tandermann/iucn_extinction_simulator/blob/master/data/iucn_sim_output/mammalia/future_sim_mode_0/extinction_probs_over_next_100_years.txt

Does that help?

**Comment by XuWeiEvo** [comment]
Thank you very much for your response! If I understand correctly, the file "extinction_probs_over_next_X_years.txt" contains the probabilities associated with species extinction. This information corresponds to the frequency of species displayed in all simulation iterations found in the "te_all_species.txt" file, which tells the timing of extinction for each species in each iteration (unit=year). If a species does not go extinct in a particular iteration, the corresponding value will be empty or marked as NA.

**Comment by tandermann** [comment]
yes exactly, you should get the same value for each species as in the `extinction_probs_over_next_X_years.txt ` file if you count the number of non-empty columns and divide by the number of columns (= number of simulation replicates) in the `te_all_species.txt` file. The values show the number of years from present when a given species was simulated as extinct.

**Comment by XuWeiEvo** [comment]
Thank you so much for your help!
